### ISSUE TITLE
[Feature Req/Enhancement] avoid clicking two buttons

### ISSUE THREAD

**Issue by FabKre** [linuxmuster/linuxmuster-linbo-gui#11]
UIX-Ideas to avoid clicking two different buttons to start OS
- double-left-click on OS to do standard-action (i.e. start synchronized). You'd still double-click, but the cursor must not be moved onto another button.
- hide OS-start-options in the UI: left click to do standard-action, right-click or click-hold to show options/context-menu
- select OS on hover, not on left-click. left click to do standard-action.

**Comment by dorianim** [comment]
Nice ideas!
I think it would make sense to combine the first and third of your suggestions:
An OS is selected on hover and the default action can be executed by double-click.
I would not hide the action buttons, as that could be confusing.
Maurice Cazautet also suggested that it would make sense to keep to old layout (on big button with the default action and small ones for the other actions) as it is also used in the WebUI.
I am think I will make it possible to choose between the old and the current layout using a configuration parameter.
(eg. "UseMinimalLayout=yes" to enable the new Layout)

**Comment by dorianim** [comment]
I have implemented the old layout. :)
The new one can be used by setting the `UseMinimalLayout = yes` in the `[LINBO]` block of the start.conf.
This is what it looks like:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/30153207/102696023-a8537200-422b-11eb-943e-289a0a015e08.gif)

I will also implement the suggestions of @FabKre though.

**Comment by dorianim** [comment]
Hovering now selects the OS and double-clicking executes the default action :slightly_smiling_face:
