### ISSUE TITLE
Move icons into place

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-linbo-gui#12]
According to what @kiarn said [over here](https://github.com/linuxmuster/linuxmuster-webui7/issues/162), the new OS icons have to be placed in /srv/linbo/icons .
(note: all the new icons can be found [here](https://github.com/linuxmuster/linuxmuster-linbo-gui/tree/master/build/icons) )
@HappyBasher can you implement this in the gui .deb package?
And by the way Merry Christmas :smiley:

**Comment by kiarn** [comment]
Hello,

`/srv/linbo/icons` is convenient because it is already listed by the Webui, but it can be another path. The most important thing is to define the breakpoint between png and svg. I'm currently planing to display svg in the select only if the package `linuxmuster-linbo-gui7` is installed.

**Comment by dorianim** [comment]
Hi,

The icons will be contained in `linuxmuster-linbo-gui7` so they won't be there when it isn't installed.
I would suggest: Just check if the icons are there and if they are, use the svg ones, otherwise fall back to png.

**Comment by dorianim** [comment]
@HappyBasher What is the correct way to do this?
(I don't have a lot of experience with building .deb packages)

**Comment by dorianim** [comment]
I figured out how to do it :)
The icons are now placed in /srv/linbo/icons
