### ISSUE TITLE
client info shows html bold tags

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-linbo-gui#13]
You are making good progress :-). But I fear the client info has a bug:

![gui-client-infos-alpha03](https://user-images.githubusercontent.com/1845363/103092950-3bf4bc00-45f9-11eb-8674-b11dd1833a90.png)

**Comment by dorianim** [comment]
Yep, that's definitely a Bug 🙃
I'll look into that tomorrow.

**Comment by HappyBasher** [comment]
Is not hurry ...

**Comment by dorianim** [comment]
I think, I found the issue, 
I excluded the html parser from the Qt build, I'll include it and check if it solves the issue :)

**Comment by dorianim** [comment]
I can confirm that this was the problem :)

**Comment by HappyBasher** [comment]
Unfortunately I can not confirm this. Now it looks like this:
![gui-client-infos-alpha03](https://user-images.githubusercontent.com/1845363/103152684-ac7f1280-478a-11eb-9fa2-5e5c7e0ed73e.png)

**Comment by dorianim** [comment]
Well ... 😅
All the html tags are already fixed, thad was a bau, but they should not be visible.
As I changed something in the Qt configuration, you have to do a full rebuild (delete the build32 and build64 dirs) or use the archives that are present in the latest release :)

**Comment by HappyBasher** [comment]
Yep, fixed!
