### ISSUE TITLE
Additional infos not displayed

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-linbo-gui#25]
I'm testing the new GUI, but it does not show the additional infos like group, RAM, IP, ...

![grafik](https://user-images.githubusercontent.com/708888/104673768-f9646200-5714-11eb-9e9d-8910f6a48202.png)

The resolution of my virtual console is 800x600. Is this to small for the new GUI? Or is there another setting to display these infos?

PS: The new GUI looks really great :heart:

**Comment by dorianim** [comment]
You need to press F1 to make them appear ;)
