### ISSUE TITLE
direction of splash screen spinner

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-linbo-gui#34]
I'm not sure if it's just me, but it feels more natural, if the spinner would spin clock wise and not counter clock wise. 

IMHO (at least for the splash screen) it would be nicer if it is thinner, too, so it does not overlap with the logo inside the spinner.

**Comment by dorianim** [comment]
Hi @zefanja,
The splashscreen is handled in the linuxmuster-linbo repo :)
I am moving this issue. EDIT: looks like I can't
Please create a new issue in the linuxmuster-linbo repo :)
Regards, Dorian
