### ISSUE TITLE
gui default background color

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-linbo-gui#40]
Please set the default background color of the gui to 394f5e, the organisation's corporate background color.

**Comment by dorianim** [comment]
Isn't it 0c2842 ?
(This is the color of the middle of the Linxmuster X)

**Comment by HappyBasher** [comment]
I took the hex code from the wallpaper, but it is not the same as from Hompage & ask header line.
Therefore we should take 2a4457 (RGB: 16,5/26,7/34,1). I never realized that the color of the dot is different.

**Comment by dorianim** [comment]
Ok, then we'll take 2a4457.
