### ISSUE TITLE
64bit gui does not start because of missing shared libraries.

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-linbo-gui#5]
List of shared libs missing:
```
libdrm.so.2
libexpat.so.1
libfontconfig.so.1
libfreetype.so.6
libjbig.so.0
libjpeg.so.8
liblcms2.so.2
libmng.so.2
libtiff.so.5
```

**Comment by HappyBasher** [comment]
libfreetype.so.6 is also missing

**Comment by HappyBasher** [comment]
Also libdrm.so.2.

**Comment by HappyBasher** [comment]
The needed libraries should not be source tree. We will collect them from the buildsystem during debian package build and provide them in the deb only.

**Comment by dorianim** [comment]
That makes sense, I'll change that.
The missing libraries are probably caused by missing packages on the build system, which I forgot to install automatically, I'll look into that.

**Comment by dorianim** [comment]
Well... that's strange I just set up an entirely clean ubuntu server 18.04, cloned the repo, ran build.sh and everything works.
Could you supply the log of the entire build process?

**Comment by HappyBasher** [comment]
Unfortunately I do not have any log of the build. After the build I packed the whole tree under linbofs64 but that was not sufficient as it turned out. Tomorrow I will give it another try.

**Comment by dorianim** [comment]
How did you deploy the fiiles? I just copied over the contens of linbofs64 to a running Linbo instance via rsync.
Please note: You will have to delete the build33 and build64 directories before building, otherwise Qt won't be built again.

**Comment by HappyBasher** [comment]
> I just copied over the contens of linbofs64  

So I did it too.

**Comment by HappyBasher** [comment]
Works now. :+1:
