### ISSUE TITLE
Error when trying to create new diff image

### ISSUE THREAD

**Issue by sharky009** [linuxmuster/linuxmuster-linbo-gui#52]
Hi,

One thing i've noticed today is that the gui throws an error if you try to create an new rsync image. Its possible to overwrite the existing cloop, but not to create a complete new image also. 
Is there a reason for this behaviour? Has the image name to be set into the start.conf before the image was created? 

Greetings 
Pascal

**Comment by dorianim** [comment]
Hi Pascal,

The current implementation of a "differential" image as documented [here](https://docs.linuxmuster.net/de/latest/clients/linbo/linbo-imagingscreen.html) is no longer supported and will soon be dropped. However, a totally new base for the imaging solution is in the works, so stay tuned :)
This would be an issue for the [linuxmuster-linbo repo](https://github.com/linuxmuster/linuxmuster-linbo) though, as the GUI is just there to for controlling Linbo. The actual imaging is done over there.

The new Linbo GUI (which is what this repo contains) does not come with this feature anymore, so I am closing this issue.

Regads,
Dorian
