### ISSUE TITLE
Register a client does not work if not already registered (?)

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-linbo-gui#53]
When trying to enter the admin menu with a non registered client this fails, possibly due the missing start.conf. This makes it impossible to register a device via the new linbo gui.

**Comment by dorianim** [comment]
This should not be the case. I think it works on my test system but I will take a look at it again.

**Comment by dorianim** [comment]
You are correct, it does not work...
I really need to create some automated testa for such things.
