### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-linbo-gui#54]
1. Its not possible to get the extended information pressing F1 at all time. 
This only works in the main menu. Either the info F1 should disappear when not possible or it should be possible to trigger at all time.

2. It would be nice if the extendet information are displayed to keep them displayed and not auto hiding again when entering a task.
 
3.  Hitting ESC should always go back to the main screen (eg. from the admin menu but also when a task is done).

**Comment by dorianim** [comment]
Ok, so I will
1. Leave the extended information menu always usable
2. make ecs quit "xyz finished" page
3. make esc quit the admin menu

Did I miss something?

**Comment by Buster-de** [comment]
IP as first and only detail that is presented always, doesn't tell me much. I'd prefer to see computer name and assigned group. Is there an option to have details (F1) enabled by default?

**Comment by dorianim** [comment]
Showing the IP by default was a decision made on the linuxmuster forum. I think i will make it possible to show the details by default using a start.conf parameter.

**Comment by dorianim** [comment]
The parameter `clientDetailsVisibleByDefault` in the `[LINBO]` section of the start.conf can now be used to make the client details visible by deefault.

**Comment by dorianim** [comment]
This will also come to the WebUI:
https://github.com/linuxmuster/linuxmuster-webui7/issues/177
