### ISSUE TITLE
Options Missing in Linbo

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-linbo-gui#65]
Since the recent changes which allowed running linbo in ridiculous small resolutions we introduced another problem. Linbo does not show the management options:
![grafik](https://user-images.githubusercontent.com/26460239/130071991-4bceefd0-75f1-4a81-8826-96b07ed772fe.png)

Any suggestions to debug this?

**Comment by dorianim** [comment]
I think, I already fixed this here: https://github.com/linuxmuster/linuxmuster-linbo-gui/commit/9b6dab6b2e78dc14de31cf6a220a7c8e4852cf80

It was released in v7.0.3, please update and try again :)

**Comment by dorianim** [comment]
@PLanB2008 have you tested this?

**Comment by dorianim** [comment]
@PLanB2008 ?

**Comment by dorianim** [comment]
Clsing this due to inactivity. Feel free to reopen if the problem persists.
