### ISSUE TITLE
Image erstellen und hochladen funktioniert nicht

### ISSUE THREAD

**Issue by garblixa** [linuxmuster/linuxmuster-linbo-gui#66]
Wenn es noch kein Basisimage gibt, dann kann man mit "erstellen + hochladen" kein Image erstellen.

Man muß das Image zuerst mit dem Button "erstellen" kreieren, neu starten, anschließend kann man es hochladen.

**Comment by dorianim** [comment]
Hi @garblixa 

Ok, das ist merkwürdig. Schau ich mir mal bei Gelegenheit an.

**Comment by dorianim** [comment]
Gibt es eine Fehlermeldung?

**Comment by garblixa** [comment]
Leider keine Fehlermeldung. Man landet nur in der vorherigen Übersicht mit den Admin Möglichkeiten von Linbo.

**Comment by dorianim** [comment]
Benutzt du linbo 3 oder 4?

**Comment by garblixa** [comment]
Mit linbo Version 3 hatte ich das getestet. Also die Stable Version.

**Comment by garblixa** [comment]
Ich meinte das war die Version 2.4.3-4. Sorry.

**Comment by dorianim** [comment]
Hast du bei BaseImage in der start.conf etwas eingetragen?

**Comment by garblixa** [comment]
Nein, es gibt ja zu diesem Zeitpunkt noch keines.

**Comment by dorianim** [comment]
Ahaaa. Ok, daran scheint es zu liegen. Das hatte ich so nicht vorgesehen. Du kannst einfach einen neuen Namen da eintragen, auch wenn es das Image noch nicht gibt. Aber ich fixe das.

**Comment by dorianim** [comment]
Sollte in 084156b6b653893ec34f0ba55431789779deefbf behoben sein
Ich hab einen neuen release angestoßen; muss noch kompilieren: https://github.com/linuxmuster/linuxmuster-linbo-gui/actions/runs/1508326475
Sobald das fertig ist, kannst du über das neue [lmn71 repo](https://ask.linuxmuster.net/t/linuxmuster-net-7-1-testing) updaten, oder die .deb Datei von der release Seite herunterladen.

**Comment by garblixa** [comment]
Hmm, Moment. Wenn ich in der Linuxmuster GUI/LINBO eine neue Konfiguration erstelle, dann sehe ich in der GUI unter OS/BasisImage: None. In der start.conf des Templates steht win10.cloop. Dieses Image existiert aber nicht.

**Comment by dorianim** [comment]
Ok, also steht doch was in der start.conf. Dann müssen wir weiter suchen. Schau mal bitte in die Datei `/tmp/linbo.log`. Am Besten, du leerst sie mit `echo "" > /tmp/linbo.log`, versuchst dann das image zu erstellen, und postest dann den Inhalt der Datei.

**Comment by garblixa** [comment]
Hallo Dorian,
leider habe ich das System, auf dem das aufgetreten ist, momentan nicht im Zugriff und konnte nicht nachsehen. Ich habe jetzt versucht das auf meinem Testsystem nachzustellen. Tatsächlich ist es so, daß der Fehler nur auftritt, wenn BaseImage in start.conf leer ist. Sobald irgendein Image drinnen steht, auch wenn es nicht existiert, dann funktioniert alles wie es sein soll. Dein Fix ist also dann doch richtig und das Thema wäre damit gelöst.
Danke für die schnelle Bearbeitung!

**Comment by dorianim** [comment]
Okay, cool :+1:
Das Update ist jetzt verfügbar.
