### ISSUE TITLE
Add device role field to register page

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-linbo-gui#7]
We could have a field for the device role on the register page, implemented as a collapsible menu, with default on classroom-studentcomputer:

classroom-studentcomputer
classroom-teachercomputer
faculty-teachercomputer
staffcomputer

**Comment by dorianim** [comment]
That's true.
How would I pass that to ```linbo_cmd register```?
Probably, it would be most efficient to use the same keys as in devices.csv like ```classroom-studentcomputer``` and just pass them as another parameter?

**Comment by HappyBasher** [comment]
Yes, I will implement this as parameter no. 8:
`linbo_cmd register server user password room hostname ip group role`

**Comment by HappyBasher** [comment]
See https://github.com/linuxmuster/linuxmuster-linbo/commit/7d97af70a245391811975b630c4bd375ba67bb42

**Comment by HappyBasher** [comment]
Oh, how comfortable, github detects the reference itself. :-)
