### ISSUE TITLE
provide an option to skip auto partitioning

### ISSUE THREAD

**Issue by Buster-de** [linuxmuster/linuxmuster-linbo-gui#74]
As an admin, who deploys a vast amount of computers in multiple rooms, you have computers that finish early and you want to reboot them to check if all is okay, while the majority of computers still need auto partioning enabled so you cant disable auto partitioning.

Give an option to manually skip auto partioning like you can cancel auto start of operating system, e.g. with an 3 sec countdown with abort and skip on pressing ESC button.

**Comment by dorianim** [comment]
Adding a cancel button should be simple. But adding another timeout would be kind of an effort and would also require changes in the start.conf spec and therefor also affect the webui.

**Comment by Buster-de** [comment]
I dont quite understand. If you can do buttons but not a timeout, how would it still be auto partitioning?

**Comment by HappyBasher** [comment]
Anyway I don't think it's a good idea to give the standard user the option to cancel autopartitioning. That presupposed that the user in this case knows exactly what he is doing. This will in the end give the admin more work due to operating errors and contradicts the higher-level principle to keep it simple for the user.

**Comment by dorianim** [comment]
Yes, that's a fair argument.

**Comment by Buster-de** [comment]
The user can also cancel autostart without knowing what this means. The user can choose between multiple operating systems in multi-boot environments without having to understand what this means. People who don't know what is happening just wait for the timeout and autopartitioning would happen as well as autostart would happen.

The IT staff is also the user of this software. Thousands and thousands of people over the years had no problem using imaging systems in automatic operating modes and not pressing buttons they dont know about without any introduction. So why should it now be an issue when the 2nd group of users - the IT staff - get an option to make their work easier?

**Comment by HappyBasher** [comment]
After startup Linbo shows the _user_ interface. Starting and repairing operating systems on demand are user tasks. Client partitioning is an admin task. Admin interface is password protected for a good reason.

**Comment by Buster-de** [comment]
Who said skipping auto partitioning could not ask for login?

**Comment by HappyBasher** [comment]
So you are the opinion we should waste the time of 3 developers (linuxmuster-linbo7, linuxmuster-linbo-gui, linuxmuster-webui7) for this shit, that noone really needs? Weired.
No, using autopartition to deploy operating systems to machines is the opposite of making the work of admins easier.

**Comment by dorianim** [comment]
Let's stay calm :)
But I do also think, that it does not make a lot of sense to implement it like this. Adding a login to the cancellation of an operation is nothing that I accounted for when structuring the code. This would require a major rewrite, and I do not have the time to do that.

**Comment by Buster-de** [comment]
> No, using autopartition to deploy operating systems to machines is the opposite of making the work of admins easier.

Please elaborate.

**Comment by dorianim** [comment]
As far as I understood you, you want to have an option to automatically partition a computer ONCE and not again after that. Is that correct?

**Comment by HappyBasher** [comment]
This: https://github.com/linuxmuster/linuxmuster-linbo7/issues/62#issuecomment-1076313460

**Comment by dorianim** [comment]
We decided to close this issue as there is a better way to solve your usecase (see https://github.com/linuxmuster/linuxmuster-linbo7/issues/62#issuecomment-1076313460)

If you still want to have this feature, I am happy to look at a pull request :)
