### ISSUE TITLE
Upload does not see qcow2 images

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-linbo-gui#77]
The image upload function in the admin section does not see qcow2 images lying around in the cache. linbo_cmd does the job:
```
# linbo_cmd listimages /dev/sda4
/cache/focal-v1.0.qcow2
/cache/win10-efi.qcow2
```
Observed with linuxmuster-linbo-gui7 7.0.5.

**Comment by dorianim** [comment]
Did you restart the gui after adding the image?

**Comment by dorianim** [comment]
What is even the usecase of this? Is there a case where an image exists which is not in the start.conf?

**Comment by HappyBasher** [comment]
> Did you restart the gui after adding the image?

This issue persists over reboots and depends not on added new images.

**Comment by HappyBasher** [comment]
> What is even the usecase of this?

To select an image to upload.

> Is there a case where an image exists which is not in the start.conf?

Nope.

BTW, with linbo_gui 7.1.0 I am able to select an image to upload.

**Comment by dorianim** [comment]
Oh, ok. If it's working with the 7.1.0, then it's already fixed. I won't backport this to the old version.

**Comment by HappyBasher** [comment]
Then you leave the current stable version with a bug. Users were not able to create an image offline and upload it later.

**Comment by dorianim** [comment]
It can be done using the terminal.

**Comment by dorianim** [comment]
Changed my mind, update is coming ...
