### ISSUE TITLE
debian packaging

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-linbo-gui#8]
Added debian folder with packaging infrastructure. Debs can be build now with the script `debian/mkdeb.sh`.
Let me know when we can publish a first package.

**Comment by dorianim** [comment]
Very cool :)
But I noticed that there are lots of dependencies listed in the control file, is that actually necessary? I think they are only required for building.

**Comment by HappyBasher** [comment]
Yes, this are only build depends, not for the binary package.

**Comment by HappyBasher** [comment]
The package contains only two archives with the 32 and 64 bit versions of the gui together with the dependend libs. They will be installed on the server in /srv/linbo. The linbo client uses automatically the new gui if it is present.
To get rid of it simply deinstall the package.
A test version of the package can be installed from the lmn7-testing repo.

**Comment by dorianim** [comment]
That is really cool :D
I'll try it out tomorrow

**Comment by dorianim** [comment]
I just tried it out and the installation works :)
I noticed though, that some text is not being displayed ... I think this happens where I didn't explicitly define the font name to use, so it should be easy to fix.

**Comment by dorianim** [comment]
Fixed the text issue, see #9

**Comment by HappyBasher** [comment]
build.sh complains about not being root because it uses apt. But there is not need to be root because apt is used with sudo. In general debian packages are build not as root.

**Comment by HappyBasher** [comment]
I have done a fresh checkout to build a new package and the build process does not behave as before. First there is the root complaint (see above). And then there are questions:

```
Selecting Qt Edition.

Type 'c' if you want to use the Commercial Edition.
Type 'o' if you want to use the Open Source Edition.

Which edition of Qt do you want to use? o

This is the Qt Open Source Edition.
 
You are licensed to use this software under the terms of
the GNU Lesser General Public License (LGPL) version 3
or the GNU General Public License (GPL) version 2.
 
Type 'L' to view the GNU Lesser General Public License version 3 (LGPLv3).
Type 'G' to view the GNU General Public License version 2 (GPLv2).
Type 'y' to accept this license offer.
Type 'n' to decline this license offer.
 
Do you accept the terms of either license? y
```

And later it breaks with:
`./build.sh: Zeile 93: -opensource: Befehl nicht gefunden`

**Comment by dorianim** [comment]
Ahh, yes
I have changed how the different build scripts are generated and missed out on this... I'll fix it

**Comment by dorianim** [comment]
Should work now.
( https://github.com/linuxmuster/linuxmuster-linbo-gui/releases/tag/7.0.1-Alpha01-1 )

**Comment by HappyBasher** [comment]
Build works now, but dependend libs are missing again in the lib dir, so the gui does not start:
```
libdrm.so.2
libevdev.so.2.1.20
libexpat.so.1
libffi.so.6.0.4
libfontconfig.so.1
libfreetype.so.6
libglib-2.0.so.0.5600.4
libgobject-2.0.so.0.5600.4
libgudev-1.0.so.0.2.0
libinput.so.10.13.0
libjbig.so.0
libjpeg.so.8
liblcms2.so.2
libmng.so.2
libmtdev.so.1.0.0
libtiff.so.5
libwacom.so.2.6.1
libxkbcommon.so.0.0.0
```

**Comment by HappyBasher** [comment]
I copied the missing libs over by hand, so that I am able to build a functioning package: see linuxmuster-linbo-gui7 0.2 in lmn7-testing.

**Comment by dorianim** [comment]
I'll create an automation for that as soon as I have time for it :)

**Comment by dorianim** [comment]
I just removed all dependencies form the source tree and now they are copied in place by the build script.

**Comment by dorianim** [comment]
@HappyBasher Please let me know if it works for you :)

**Comment by HappyBasher** [comment]
@CodeCrafter912 libexpat.so.1 is missing otherwise all libs are on board.

**Comment by dorianim** [comment]
Hmm.. where does that come from?
ldd does not show it as a dependency on my system (linbo 2.4.1):
```
~ # ldd /usr/bin/linbo_gui 
	linux-vdso.so.1 (0x00007ffc1229a000)
	libmtdev.so.1 => /lib/libmtdev.so.1 (0x00007f74dd2f7000)
	libinput.so.10 => /lib/libinput.so.10 (0x00007f74dd0bd000)
	libudev.so.1 => /lib/libudev.so.1 (0x00007f74dce9f000)
	libxkbcommon.so.0 => /lib/libxkbcommon.so.0 (0x00007f74dcc60000)
	libdl.so.2 => /lib/libdl.so.2 (0x00007f74dca5c000)
	libpthread.so.0 => /lib/libpthread.so.0 (0x00007f74dc83d000)
	libstdc++.so.6 => /lib/libstdc++.so.6 (0x00007f74dc4b4000)
	libm.so.6 => /lib/libm.so.6 (0x00007f74dc116000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x00007f74dbefe000)
	libc.so.6 => /lib/libc.so.6 (0x00007f74dbb0d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f74de4b9000)
	libevdev.so.2 => /lib/libevdev.so.2 (0x00007f74db8f3000)
	librt.so.1 => /lib/librt.so.1 (0x00007f74db6eb000)
	libwacom.so.2 => /lib/libwacom.so.2 (0x00007f74db4e1000)
	libgudev-1.0.so.0 => /lib/libgudev-1.0.so.0 (0x00007f74db2d7000)
	libgobject-2.0.so.0 => /lib/libgobject-2.0.so.0 (0x00007f74db083000)
	libglib-2.0.so.0 => /lib/libglib-2.0.so.0 (0x00007f74dad6c000)
	libffi.so.6 => /lib/libffi.so.6 (0x00007f74dab64000)
	libpcre.so.3 => /lib/libpcre.so.3 (0x00007f74da8f2000)
```

**Comment by HappyBasher** [comment]
Here on Ubuntu 18.04.5:
```
ldd build/linbofs64/usr/bin/linbo_gui 
	linux-vdso.so.1 (0x00007fff6ae87000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f6de8a3b000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f6de8787000)
	libmtdev.so.1 => /usr/lib/x86_64-linux-gnu/libmtdev.so.1 (0x00007f6de8582000)
	libinput.so.10 => /usr/lib/x86_64-linux-gnu/libinput.so.10 (0x00007f6de8348000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f6de812a000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f6de7eeb000)
	libdrm.so.2 => /usr/lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f6de7cda000)
	libmng.so.2 => /usr/lib/x86_64-linux-gnu/libmng.so.2 (0x00007f6de7a5e000)
	libtiff.so.5 => /usr/lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f6de77e7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f6de75e3000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f6de73c4000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6de703b000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6de6c9d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6de6a85000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6de6694000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6de9b7a000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f6de6462000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f6de6230000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f6de6013000)
	libevdev.so.2 => /usr/lib/x86_64-linux-gnu/libevdev.so.2 (0x00007f6de5df9000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f6de5bf1000)
	libwacom.so.2 => /usr/lib/x86_64-linux-gnu/libwacom.so.2 (0x00007f6de59e7000)
	libjpeg.so.8 => /usr/lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f6de577f000)
	liblcms2.so.2 => /usr/lib/x86_64-linux-gnu/liblcms2.so.2 (0x00007f6de5527000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f6de5301000)
	libjbig.so.0 => /usr/lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f6de50f3000)
	libgudev-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgudev-1.0.so.0 (0x00007f6de4ee9000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f6de4c95000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f6de497e000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f6de4776000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f6de4504000)
```

**Comment by dorianim** [comment]
Interesting... you have so many more dependencies than I do ...
This is ldd output on my ubuntu 18.04 build system:
```
root@linbo-build:~/linuxmuster-linbo-gui/build/buildGUI64/build# ldd linbo_gui
	linux-vdso.so.1 (0x00007fffaa90b000)
	libmtdev.so.1 => /usr/lib/x86_64-linux-gnu/libmtdev.so.1 (0x00007f9a0de64000)
	libinput.so.10 => /usr/lib/x86_64-linux-gnu/libinput.so.10 (0x00007f9a0dc2a000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f9a0da0c000)
	libxkbcommon.so.0 => /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f9a0d7cd000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9a0d5c9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9a0d3aa000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9a0d021000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9a0cc83000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9a0ca6b000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9a0c67a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9a0f026000)
	libevdev.so.2 => /usr/lib/x86_64-linux-gnu/libevdev.so.2 (0x00007f9a0c460000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9a0c258000)
	libwacom.so.2 => /usr/lib/x86_64-linux-gnu/libwacom.so.2 (0x00007f9a0c04e000)
	libgudev-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libgudev-1.0.so.0 (0x00007f9a0be44000)
	libgobject-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0 (0x00007f9a0bbf0000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f9a0b8d9000)
	libffi.so.6 => /usr/lib/x86_64-linux-gnu/libffi.so.6 (0x00007f9a0b6d1000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f9a0b45f000)
```

I have a theory why this is the case, but for now I will just copy all libs that ldd requires. Doing this might increase the size of the archive but it will ensure that it works on every build system.

**Comment by dorianim** [comment]
Should work now. Please try again :)

**Comment by HappyBasher** [comment]
Works! :-)

**Comment by HappyBasher** [comment]
I will optimize this during package build because there are libs which are already present in linbofs and must therefore not provided within the gui package.

**Comment by dorianim** [comment]
That makes sense.
I think it would also make sense to move the debian directory into the build dir and make the main build script call mkdeb.sh. Do you think so as well?

**Comment by HappyBasher** [comment]
> I think it would also make sense to move the debian directory into the build dir and make the main build script call mkdeb.sh. Do you think so as well?  

Nope, the debian directory has to be always in the root of the source tree to work. This is debian specification.

**Comment by dorianim** [comment]
Oh, ok, I didn't know that.
But I still think that the main build.sh script should build the packages (just to make it more intuitive)

**Comment by HappyBasher** [comment]
> I think it would also make sense to move the debian directory into the build dir and make the main build script call mkdeb.sh. Do you think so as well?  

Nope, the debian directory has to be always in the root of the source tree to work. This is debian specification.

**Comment by HappyBasher** [comment]
> But I still think that the main build.sh script should build the packages (just to make it more intuitive)  

Do it. Contrary to what I just said, I don't have to change anything in the `mkdeb.sh` script.

**Comment by dorianim** [comment]
done.

**Comment by HappyBasher** [comment]
Had to add packages `libmtdev-dev libwacom-dev` to generic build script for 64 bit version to avoid dependency complaints.

**Comment by dorianim** [comment]
I just released [7.0.1-Alpha02](https://github.com/linuxmuster/linuxmuster-linbo-gui/releases/tag/7.0.1-Alpha02)

**Comment by dorianim** [comment]
I automated the build process using GitHub actions :) 
Now every time a tag which starts with "v" is created, GitHub automatically builds the gui packages, creates a release and uploads all artifacts as an asset to the release (eg.: https://github.com/linuxmuster/linuxmuster-linbo-gui/releases/tag/v7.0.1-Alpha03-01 )
We could even automate the upload to the lmn testing repo, for example with curl :)
What do you think about that @HappyBasher ?

**Comment by HappyBasher** [comment]
Sounds cool. I'll check this next week.

**Comment by dorianim** [comment]
@HappyBasher 
Could you create a rule to move all icons to `/srv/linbo/icons` :slightly_smiling_face: ? (To close #12)

**Comment by dorianim** [comment]
The build process is working, closing this.
